### ISSUE TITLE
Author Room Class

### ISSUE THREAD

**Issue by EdWard680** [HCRHS-Code-Club/school-navigator#2]
Well we have to start some where. You can refer to the class structure design file in the repo for reference. 
Basically the simplest class is Room. All it needs is to be an object which contains and ID which you can get, set, and construct.
If this means nothing to you I suggest you brush up on your java then ask me here.

**Comment by kongwei1** [comment]
Sounds good I understand it just one thing, do you want the ID# to just be
the real room number 100s-900s?

**Comment by zethra** [comment]
So are we starting work on this again Eric?

**Comment by EdWard680** [comment]
@kongwei1 The ID should be generally unrelated to the room number. I have edited the class structure file. Room number info should be stored as a string. If you can think of any useful information that is unique per room, add it to the Room class as you see fit.

**Comment by kongwei1** [comment]
In the class room, is that where you want me to store the input from the
user for room name?

**Comment by EdWard680** [comment]
User input shouldn't interface directly with the room class. It will just be used as a way to tie together room IDs with room info.
